rvm:
  - 1.9.3
  - jruby-19mode
  - rbx-2
  - 2.0.0
  - 2.1.1

install:
  - "travis_retry bundle install"

before_script: "sudo ntpdate -ub ntp.ubuntu.com pool.ntp.org; true"
script: "bundle exec rake clean spec cucumber"

gemfile:
  - gemfiles/3.2.gemfile
  - gemfiles/4.0.gemfile
  - gemfiles/4.1.gemfile

matrix:
  fast_finish: true
  allow_failures:
    - rvm: jruby-19mode
    - rvm: rbx-2
