rvm:
  - 1.9.2
  - 1.9.3
  - jruby-19mode
  - rbx-19mode
  - 2.0.0
  - 2.1.0

install:
  - "travis_retry bundle install"

before_script: "sudo ntpdate -ub ntp.ubuntu.com pool.ntp.org; true"
script: "bundle exec rake clean test cucumber"

gemfile:
  - gemfiles/3.0.gemfile
  - gemfiles/3.1.gemfile
  - gemfiles/3.2.gemfile
  - gemfiles/4.0.gemfile
  - gemfiles/4.1.gemfile

matrix:
  fast_finish: true
  allow_failures:
    - rvm: jruby-19mode
    - rvm: rbx-19mode

  exclude:
      - rvm: 1.9.2
        gemfile: gemfiles/4.0.gemfile
      - rvm: 1.9.2
        gemfile: gemfiles/4.1.gemfile
